//
//  ConsolePresenter.swift
//  SwiftRCON
//
//  Created by LeeSeGun on 2022/01/10.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConsolePresentationLogic {
    func presentFetchLogs(response: Console.FetchLog.Response)
    func presentRealtimeLogs(response: Console.FetchLog.Response)
}

class ConsolePresenter: ConsolePresentationLogic {
    weak var viewController: ConsoleDisplayLogic?
    
    func presentFetchLogs(response: Console.FetchLog.Response) {
        viewController?.displayFetchLogs(viewModel: .init(logs: response.logs))
    }
    
    func presentRealtimeLogs(response: Console.FetchLog.Response) {
        viewController?.displayRealtimeLogs(viewModel: .init(logs: response.logs))
    }
}
