//
//  PlayersPresenter.swift
//  SwiftRCON
//
//  Created by LeeSeGun on 2022/01/10.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlayersPresentationLogic {
    func presentFetchPlayerList(response: Players.FetchPlayerList.Response)
}

class PlayersPresenter: PlayersPresentationLogic {
    weak var viewController: PlayersDisplayLogic?
    
    // MARK: FETCHED
    func presentFetchPlayerList(response: Players.FetchPlayerList.Response) {
        viewController?.displayFetchPlayerList(viewModel: .init(players: response.players))
    }
}
