//
//  SettingModels.swift
//  SwiftRCON
//
//  Created by LeeSeGun on 2022/01/18.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Setting {
    // MARK: Use cases
    
    enum Something {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    enum SaveServer {
        struct Request {
            var ip: String
            var port: String
            var password: String
        }
        struct Response {
            var success: Bool
            var message: String?
        }
        struct ViewModel {
            var success: Bool
            var message: String?
        }
    }
}
