//
//  SettingPresenter.swift
//  SwiftRCON
//
//  Created by LeeSeGun on 2022/01/18.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingPresentationLogic {
    func presentSomething(response: Setting.Something.Response)
}

class SettingPresenter: SettingPresentationLogic {
    weak var viewController: SettingDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Setting.Something.Response) {
        let viewModel = Setting.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
